spring:
  datasource:
    url: jdbc:mysql://localhost:3306/luxe_restaurant?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: duynguyen123#

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

  flyway:
    baseline-on-migrate: true

  ai:
    openai:
      api-key: AIzaSyAijcwrpna9rYtaLQZl8BoeNZI6cBh9bU4
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: v1beta/openai/chat/completions
        options:
          model: gemini-2.5-flash

  mail:
    host: smtp.gmail.com
    port: 587
    username: duycter0202@gmail.com
    password: sqnbidcnybaosnqi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true